---
- name: Deploy Nexus Repository OSS in Docker
  hosts: nexus
  become: yes
  vars:
    nexus_container_name: nexus
    nexus_image: sonatype/nexus3:3.80.0
    nexus_port: 8081
    nexus_data_dir: /opt/nexus-data

  tasks:
    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create Nexus data directory
      file:
        path: "{{ nexus_data_dir }}"
        state: directory
        owner: 200
        group: 200
        mode: '0755'

    - name: Run Nexus container
      docker_container:
        name: "{{ nexus_container_name }}"
        image: "{{ nexus_image }}"
        ports:
          - "{{ nexus_port }}:8081"
        volumes:
          - "{{ nexus_data_dir }}:/nexus-data"
        restart_policy: always
        state: started

    - name: Install firewalld
      dnf:
        name: firewalld
        state: present

    - name: Ensure firewalld is running and enabled
      systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: Open Nexus port using shell command
      shell: |
        firewall-cmd --permanent --add-port={{ nexus_port }}/tcp
        firewall-cmd --reload
